### ISSUE TITLE
Issue with OMV 4

### ISSUE THREAD

**Issue by JS-E** [OpenMediaVault-Plugin-Developers/openmediavault-sensors#12]
Hey,

I'd love to use this plugin but it seems to cause massive issues when i download and follow the instructions [here](https://bintray.com/openmediavault-plugin-developers/erasmus-testing/openmediavault-sensors/view)

Will this be fixed soon? I'd love to test it and help out where i can

**Comment by ryecoaaron** [comment]
You are downloading the version for OMV 3.x and it is known that it is broken on OMV 4.  There is work being done on it but it is going very slow.  Search the forum for the thread for status updates.

**Comment by JS-E** [comment]
Ok no sweat, thanks for the reply.
