### ISSUE TITLE
Support for upcoming OMV 5?

### ISSUE THREAD

**Issue by DavidBerdik** [OpenMediaVault-Plugin-Developers/openmediavault-sensors#13]
When OMV 4 came out, I tried unsuccessfully to contribute to porting this plugin to it, but at this point, I think it would be more valuable to port this plugin to the upcoming OMV 5. Are any of the original developers of this plugin willing to do this?

And what has changed between OMV 3 and OMV 5 that needs to be taken in to account with this plugin? If someone is familiar enough to assist me, I would be happy to help bring this plugin up-to-date.

**Comment by cptjhmiller** [comment]
It is no so much the plugin but OMV itself.

I could get the plugin working on OMV4 but during testing I found that if you changed any setting to produce different graphs it not only stop monitoring what it was monitoring but it would not change the display of the graphs and continue to display the graphs originally set.
I believe this was due to storing something in the browser cache, this would need to change if it is going to work under OMV5.

**Comment by ryecoaaron** [comment]
@DavidBerdik if you want to see what is needed to port the plugins to OMV 5.x, look at the commit log for some of the most recently ported plugins.

**Comment by DavidBerdik** [comment]
> It is no so much the plugin but OMV itself.
> 
> I could get the plugin working on OMV4 but during testing I found that if you changed any setting to produce different graphs it not only stop monitoring what it was monitoring but it would not change the display of the graphs and continue to display the graphs originally set.
> I believe this was due to storing something in the browser cache, this would need to change if it is going to work under OMV5.

I understand that this is not ideal, but wouldn't clearing your browser cache be a workaround for the problem at least?



> @DavidBerdik if you want to see what is needed to port the plugins to OMV 5.x, look at the commit log for some of the most recently ported plugins.

Okay, will do.

**Comment by lukasmrtvy** [comment]
@cptjhmiller Will You try to port this plugin to OMV5 ?

**Comment by redskinhu** [comment]
Hi
It would be great.
Thx

**Comment by ryecoaaron** [comment]
The plugin will not be ported.  Check out netdata

**Comment by DavidBerdik** [comment]
For anyone interested in using Netdata on their OMV server, there's a very helpful setup guide available here.

https://www.youtube.com/watch?v=vr4LqHUVxtM
