### ISSUE TITLE
Applying CPU Temperature Monitoring causes OMV Error

### ISSUE THREAD

**Issue by jtcmedia** [OpenMediaVault-Plugin-Developers/openmediavault-sensors#2]
Checked the 'Will monitor CPU Temperature' box, hit save then apply and OMV throws:
'Failed to execute command 'omv-mkconf sensors balls 2>&1': LoadPlugin sensors'

Error #4000:
exception 'OMVException' with message 'Failed to execute command 'omv-mkconf sensors balls 2>&1': LoadPlugin sensors' in /usr/share/openmediavault/engined/module/sensors.inc:55
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/config.inc(180): OMVModuleSensors->applyConfig()
#1 [internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
#2 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpcservice.inc(158): OMVRpcServiceAbstract->callMethod('applyChanges', Array, Array)
#4 /usr/share/openmediavault/engined/rpc/config.inc(224): OMVRpcServiceAbstract->callMethodBg('applyChanges', Array, Array)
#5 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#6 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc.inc(79): OMVRpcServiceAbstract->callMethod('applyChangesBg', Array, Array)
#8 /usr/sbin/omv-engined(500): OMVRpc::exec('Config', 'applyChangesBg', Array, Array, 1)
#9 {main}

**Comment by cptjhmiller** [comment]
You probably have unsupported hardware, check the sensors thread on the forums, it will show a few commands to run in order to add your hardware.
